Task4/src/bookd/bookd/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls', namespace='core')),
]

Task4/src/bookd/core/urls.py
from django.urls import path

from . import views

app_name = 'core'
urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('books/<int:pk>/', views.BookDetailsView.as_view(), name='book_details')
]

Task4/src/bookd/core/models.py
from django.db import models

# Create your models here.

Task4/src/bookd/core/views.py
from django.shortcuts import render
from django.views.generic import TemplateView
from django.urls import reverse

book_list = [
    {'pk': 1, 'title': 'Пикник на обочине', 'author': 'Братья Стругацкие'},
    {'pk': 2, 'title': 'Понедельник начинается в субботу', 'author': 'Братья Стругацкие'},
    {'pk': 3, 'title': 'Мастер и Маргарита', 'author': 'Булгаков М.А.'},
    {'pk': 4, 'title': 'Приключения Ийона Тихого', 'author': 'Станислав Лем'},
]


class IndexView(TemplateView):
    http_method_names = ['get']
    template_name = 'core/index.html'

    def get_context_data(self, **kwargs):
        context = super(IndexView, self).get_context_data(**kwargs)
        context['book_list'] = book_list
        return context


class BookDetailsView(TemplateView):
    http_method_names = ['get']
    template_name = 'core/book_details.html'

    def get_context_data(self, **kwargs):
        context = super(BookDetailsView, self).get_context_data(**kwargs)
        book_pk = kwargs.get('pk')

        for elem in book_list:
            if elem.get('pk') == book_pk:
                context['book'] = elem
        return context

Task4/src/bookd/core/templates/core/book_details.html
{% extends 'core/shards/base.html' %}
{% block title %}{{ book.title }}{% endblock %}
{% block content %}
    {% include 'core/shards/book_item_detailed.html' with book=book %}
{% endblock %}

Task4/src/bookd/core/templates/core/index.html
{% extends 'core/shards/base.html' %}
{% block title %}Главная страница{% endblock %}
{% block content %}
    <div class="book-list">
        <h1 class="paragraph-header">Список книг</h1>
        {% if book_list %}
            {% for book in book_list %}
                {% include 'core/shards/book_item.html' with book=book %}
            {% endfor %}
        {% else %}
            <div class="book-list__help">К сожалению, пока нет ни одной книги.</div>
        {% endif %}
    </div>
{% endblock %}

Task4/src/bookd/core/templates/core/shards/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}Bookd{% endblock %}</title>
    {% load static %}
    <link rel="stylesheet" href="{% static 'core/css/base.css' %}">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=PT+Serif">
    <link rel="stylesheet" href="{% static 'core/ext/bootstrap-4.0.0-beta.2-dist/css/bootstrap.min.css' %}">

    <script src="{% static 'core/ext/jquery-3.2.1.min.js' %}"></script>
    <script src="{% static 'core/ext/popper.min.js' %}"></script>
    <script src="{% static 'core/ext/bootstrap-4.0.0-beta.2-dist/js/bootstrap.min.js' %}"></script>
</head>
<body>
    <div class="container-fluid">
        {% include 'core/shards/page_header.html' %}
        <div class="row content-pad">
            <div class="col-md-3 content-pad__left"></div>
            <div class="col-md-6 content-pad__middle">
                {% block content %}{% endblock %}
            </div>
            <div class="col-md-3 content-pad__right"></div>
        </div>
    </div>
</body>
</html>

Task4/src/bookd/core/templates/core/shards/book_item.html
{% load static %}
<div class="book-item">
    <div class="book-item__image"><img src="{% static 'core/images/bookmark.png' %}"></div>
    <div class="book-item__description">
        <div class="book-item__header">{{ book.title }}</div>
        <div class="book-item__author">{{ book.author }}</div>
        <div><a href="{% url 'core:book_details' book.pk %}">Перейти</a></div>
    </div>
</div>

Task4/src/bookd/core/templates/core/shards/book_item_detailed.html
{% load static %}
<h1 class="paragraph-header">{{ book.title }}</h1>
<div class="book-item">
    <div class="book-item__image"><img src="{% static 'core/images/bookmark.png' %}"></div>
    <div class="book-item__description">
        <div class="book-item__header">{{ book.title }}</div>
        <div class="book-item__author">{{ book.author }}</div>
    </div>
</div>
<div class="bumper">
    <a href="{% url 'core:index' %}">Вернуться на главную</a>
</div>

Task4/src/bookd/core/templates/core/shards/page_header.html
{% load static %}
<div class="row">
    <div class="col-md-3"></div>
    <div class="col-md-6 page-header">
        <a href="{% url 'core:index' %}" class="page-header__logo">Bookd</a>
    </div>
    <div class="col-md-3"></div>
</div>