Task5/django/edu/core/urls.py
from django.urls import path

from . import views

app_name = 'core'
urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('student/<int:pk>/', views.StudentDetailsView.as_view(), name='student_details'),
    path('group/<int:pk>/', views.GroupDetailsView.as_view(), name='group_details'),
    # path('discipline/<int:pk>/', views.BookDetailsView.as_view(), name='discipline_details')
]

Task5/django/edu/edu/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls', namespace='core')),
]

Task5/django/edu/core/models.py
from django.db import models

# Create your models here.


class Faculty(models.Model):
    class Meta:
        verbose_name = 'факультет'
        verbose_name_plural = 'факультеты'

    title = models.CharField(max_length=128, verbose_name='название', unique=True)
    short_title = models.CharField(max_length=16, verbose_name='сокращение', unique=True)

    def __str__(self):
        return self.title


class Department(models.Model):
    class Meta:
        verbose_name = 'кафедра'
        verbose_name_plural = 'кафедры'

    title = models.CharField(max_length=128, verbose_name='название', unique=True)
    index = models.IntegerField(verbose_name='Индекс', unique=True)
    faculty = models.ForeignKey('core.Faculty', on_delete=models.CASCADE, verbose_name='факультет')

    def __str__(self):
        return self.combined_title

    @property
    def short_title(self):
        return '{}{}'.format(self.faculty.short_title, self.index)

    @property
    def combined_title(self):
        return '{} {}'.format(self.short_title, self.title)


class Group(models.Model):
    class Meta:
        verbose_name = 'учебная группа'
        verbose_name_plural = 'учебные группы'
        unique_together = ['index', 'department']

    index = models.IntegerField(verbose_name='индекс группы')
    department = models.ForeignKey('core.Department', on_delete=models.CASCADE, verbose_name='кафедра', null=True)

    def __str__(self):
        return self.title

    @property
    def title(self):
        return '{}-{}'.format(self.department.short_title, self.index)


class Student(models.Model):
    class Meta:
        verbose_name = 'студент'
        verbose_name_plural = 'студенты'

    first_name = models.CharField(max_length=255, verbose_name='имя')
    last_name = models.CharField(max_length=255, verbose_name='фамилия')
    group = models.ForeignKey(
        'core.Group', on_delete=models.PROTECT, verbose_name='учебная группа', blank=True, null=True)
    birth_date = models.DateField(verbose_name='дата рождения')
    current_disciplines = models.ManyToManyField(
        'core.Discipline', verbose_name='сейчас изучает', blank=True)

    def __str__(self):
        return 'Студент №{}. {} / Группа {}'.format(
            self.pk, self.get_full_name(), self.group.title if self.group else 'отсутствует')

    def get_full_name(self):
        return '{} {}'.format(self.first_name, self.last_name)


class Discipline(models.Model):
    class Meta:
        verbose_name = 'дисциплина'
        verbose_name_plural = 'дисциплины'

    title = models.CharField(max_length=255, verbose_name='название')

    def __str__(self):
        return self.title

Task5/django/edu/core/views.py
from django.shortcuts import render, get_object_or_404
from django.views.generic import TemplateView, DetailView, ListView
from django.urls import reverse

from core.models import Student, Group, Discipline, Faculty

book_list = [
    {'pk': 1, 'title': 'Пикник на обочине', 'author': 'Братья Стругацкие'},
    {'pk': 2, 'title': 'Понедельник начинается в субботу', 'author': 'Братья Стругацкие'},
    {'pk': 3, 'title': 'Мастер и Маргарита', 'author': 'Булгаков М.А.'},
    {'pk': 4, 'title': 'Приключения Ийона Тихого', 'author': 'Станислав Лем'},
]


class IndexView(ListView):
    http_method_names = ['get']
    template_name = 'core/index.html'
    model = Faculty

    def get_queryset(self):
        queryset = self.model.objects.prefetch_related('department_set', 'department_set__group_set')
        return queryset


class StudentDetailsView(TemplateView):
    http_method_names = ['get']
    template_name = 'core/student_details.html'

    def get_context_data(self, **kwargs):
        context = super(StudentDetailsView, self).get_context_data(**kwargs)
        context['student'] = get_object_or_404(Student, pk=kwargs.get('pk'))
        return context


class GroupDetailsView(DetailView):
    http_method_names = ['get']
    template_name = 'core/group_details.html'
    model = Group
    context_object_name = 'group'

Task5/django/edu/core/templates/core/group_details.html
{% extends 'core/shards/base.html' %}
{% load static %}
{% block title %}{{ book.title }}{% endblock %}
{% block style %}
    <link rel="stylesheet" href="{% static 'core/css/groups.css' %}">
{% endblock %}
{% block content %}
    <div class="content">
        <h1 class="paragraph-header">Список студентов группы {{ group.title }}</h1>
        {% if group.student_set.exists %}
            {% for student in group.student_set.all %}
                <div class="generic-item-inline">{{ student.get_full_name }}</div>
            {% endfor %}
        {% else %}
            <div>В данной группе нет ни одного студента.</div>
        {% endif %}
    </div>
{% endblock %}

Task5/django/edu/core/templates/core/index.html
{% extends 'core/shards/base.html' %}
{% load static %}
{% block title %}Главная страница{% endblock %}
{% block style %}
    <link rel="stylesheet" href="{% static 'core/css/groups.css' %}">
{% endblock %}
{% block content %}
    <div class="faculty-list">
{#        <h1 class="paragraph-header">Список факультетов</h1>#}
{#        <hr>#}
        {% if faculty_list %}
            {% for faculty in faculty_list %}
                <h1 class="paragraph-header">Факультет {{ faculty.short_title }}</h1>
                <div class="group-list">
                    {% for group in faculty.group_set.all %}
{#                        {% include 'core/shards/group_item.html' with group=group %}#}
                        <a href="{% url 'core:group_details' group.pk %}" class="generic-item-inline">
                            {{ group.title }}
                        </a>
                    {% endfor %}
                    {% for department in faculty.department_set.all %}
                        {% include 'core/shards/department_item.html' %}
                    {% endfor %}
                </div>
            {% endfor %}
        {% else %}
            <h1 class="paragraph-header">Факультеты</h1>
            <div class="faculty-list__help">К сожалению, пока нет ни одного зарегистрированного факультета.</div>
        {% endif %}
    </div>
{% endblock %}

Task5/django/edu/core/templates/core/shards/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}edu{% endblock %}</title>
    {% load static %}
    <link rel="stylesheet" href="{% static 'core/css/base.css' %}">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=PT+Serif">
    <link rel="stylesheet" href="{% static 'core/ext/bootstrap-4.0.0-beta.2-dist/css/bootstrap.min.css' %}">
    {% block style %}{% endblock %}

    <script src="{% static 'core/ext/jquery-3.2.1.min.js' %}"></script>
    <script src="{% static 'core/ext/popper.min.js' %}"></script>
    <script src="{% static 'core/ext/bootstrap-4.0.0-beta.2-dist/js/bootstrap.min.js' %}"></script>
</head>
<body>
    <div class="container-fluid">
        {% include 'core/shards/page_header.html' %}
        <div class="row content-pad">
            <div class="col-md-3 content-pad__left"></div>
            <div class="col-md-6 content-pad__middle">
                {% block content %}{% endblock %}
            </div>
            <div class="col-md-3 content-pad__right"></div>
        </div>
    </div>
</body>
</html>

Task5/django/edu/core/templates/core/shards/department_item.html
<div class="department-item">
    <div class="department-item__title">{{ department.combined_title }}</div>
    {% if department.group_set.exists %}
        {% for group in department.group_set.all %}
            <a href="{% url 'core:group_details' group.pk %}" class="generic-item-inline">
                {{ group.title }}
            </a>
        {% endfor %}
    {% else %}
        <div class="department-item__help">На данном факультете не зарегистрировано ни одной группы.</div>
    {% endif %}
</div>

Task5/django/edu/core/templates/core/shards/page_header.html
{% load static %}
<div class="row">
    <div class="col-md-3"></div>
    <div class="col-md-6 page-header">
        <a href="{% url 'core:index' %}" class="page-header__logo">Edu</a>
    </div>
    <div class="col-md-3"></div>
</div>